# Generated by Django 2.2 on 2019-04-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Donner_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=10)),
                ('Last_Donation_Date', models.DateField(default=False)),
                ('Date_O_Birth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Rating', models.IntegerField()),
                ('Feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('suggestion_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Updates_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Next_Camp_Address', models.CharField(max_length=50)),
                ('Camp_Date', models.DateField()),
                ('Timing_from', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=100)),
                ('Moblie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Blood_Donner_Model')),
            ],
        ),
    ]
